name: imdb_to_netflix
version: 1.0.1
author: Igor Caviroski
description: Convert imdb watchlist to html for Netflix search
repository: https://github.com/caviroski/imdb-to-netflix

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  args: ^1.5.0